services:
  auth:
    image: auth:v1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: >
      sh -c "npm run migrate && npm run seed && npm start"
  mysql:
    image: mysql
    env_file:
      - ".env"
    ports:
      - "3306:3306"