services:
  auth:
    image: auth:v1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
  mysql:
    image: mysql
    env_file:
      - ".env"
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: