name: VM Publish Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env    
      - run: npm ci
      - run: npm test
      - name: Remove .env file
        run: rm .env
  deploy:
    needs: 
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: "${{ secrets.SERVER_HOST }}"
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_USERNAME }}
        source: "${{ github.workspace }}"
        target: "${{ secrets.SERVER_LOCATION }}"
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd ${{ secrets.SERVER_LOCATION }} && docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} ."
      
