name: VM Publish Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm test

  deploy:
    needs: 
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: SSH and SCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp -r "${{ github.workspace }}" user@server:${{ secrets.SERVER_LOCATION }}
            ssh user@server "cd ${{ secrets.SERVER_LOCATION }} && docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} ."
      
